<a href="https://colab.research.google.com/github/MohmmadSami/AI_Labs/blob/main/AI_Lab_04(53199).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
# Question 1. Create NumPy array, split into 3 arrays, then calculate sum
# Import numpy library
import numpy as np

# Create a numpy array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

print("Original Array:", arr)

# Split array into 3 equal parts
split_arrays = np.array_split(arr, 3)

print("Split Arrays:")
for i in split_arrays:
    print(i)

# Calculate sum of all arrays
total_sum = 0

for i in split_arrays:
    total_sum += np.sum(i)

print("Total Sum of all numbers:", total_sum)


Original Array: [1 2 3 4 5 6 7 8 9]
Split Arrays:
[1 2 3]
[4 5 6]
[7 8 9]
Total Sum of all numbers: 45


In [4]:
# Question 2. Extract numbers greater than 5 and less than 15
import numpy as np

# Create numpy array
arr = np.array([2, 6, 10, 14, 18, 3, 8, 20])

print("Original Array:", arr)

# Condition: greater than 5 and less than 15
filtered = arr[(arr > 5) & (arr < 15)]

print("Numbers greater than 5 and less than 15:", filtered)


Original Array: [ 2  6 10 14 18  3  8 20]
Numbers greater than 5 and less than 15: [ 6 10 14  8]


In [5]:
# Question 3. Set Operations
# Create set1 (Even numbers 0 to 10)
set1 = {0, 2, 4, 6, 8, 10}

# Create set2 using constructor (Positive integers 1 to 10)
set2 = set([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

print("Set1:", set1)
print("Set2:", set2)

# a) Remove second and fifth element of set2
# Convert set to list because sets are unordered
set2_list = list(set2)

# Remove 2nd and 5th element (index 1 and 4)
removed_second = set2_list[1]
removed_fifth = set2_list[4]

set2.remove(removed_second)
set2.remove(removed_fifth)

print("Set2 after removing 2nd and 5th elements:", set2)

# b) Intersection of set1 and set2
set3 = set1.intersection(set2)

print("Intersection (set3):", set3)


Set1: {0, 2, 4, 6, 8, 10}
Set2: {1, 2, 3, 4, 5, 6, 7, 8, 9, 10}
Set2 after removing 2nd and 5th elements: {1, 3, 4, 6, 7, 8, 9, 10}
Intersection (set3): {8, 10, 4, 6}


In [8]:
# Question 4. Dictionary of Students
# Create dictionary named students
# Key = sapId
# Value = another dictionary with student details

students = {
    101: {"sapid": 101, "name": "Ali", "age": 20, "Semester": "Six"},
    102: {"sapid": 102, "name": "Ahmed", "age": 21, "Semester": "Six"},
    103: {"sapid": 103, "name": "Sara", "age": 22, "Semester": "Six"},
    104: {"sapid": 104, "name": "Ayesha", "age": 20, "Semester": "Six"},
    105: {"sapid": 105, "name": "Bilal", "age": 23, "Semester": "Six"}
}

print("Students Before Update:\n")

# Print in proper sequence (sorted by sapid)
for key in sorted(students):
    student = students[key]
    print("SAP ID:", student["sapid"])
    print("Name:", student["name"])
    print("Age:", student["age"])
    print("Semester:", student["Semester"])
    print("---------------------------")

# Update Semester from Six to Seven
for key in students:
    students[key]["Semester"] = "Seven"

print("\nStudents After Update:\n")

# Print again in proper format
for key in sorted(students):
    student = students[key]
    print("SAP ID:", student["sapid"])
    print("Name:", student["name"])
    print("Age:", student["age"])
    print("Semester:", student["Semester"])
    print("---------------------------")


Students Before Update:

SAP ID: 101
Name: Ali
Age: 20
Semester: Six
---------------------------
SAP ID: 102
Name: Ahmed
Age: 21
Semester: Six
---------------------------
SAP ID: 103
Name: Sara
Age: 22
Semester: Six
---------------------------
SAP ID: 104
Name: Ayesha
Age: 20
Semester: Six
---------------------------
SAP ID: 105
Name: Bilal
Age: 23
Semester: Six
---------------------------

Students After Update:

SAP ID: 101
Name: Ali
Age: 20
Semester: Seven
---------------------------
SAP ID: 102
Name: Ahmed
Age: 21
Semester: Seven
---------------------------
SAP ID: 103
Name: Sara
Age: 22
Semester: Seven
---------------------------
SAP ID: 104
Name: Ayesha
Age: 20
Semester: Seven
---------------------------
SAP ID: 105
Name: Bilal
Age: 23
Semester: Seven
---------------------------
