<a href="https://colab.research.google.com/github/MohmmadSami/AI_Labs/blob/main/AI_Lab_03(53199).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# 1. Create a 3x3 matrix with values ranging from 2 to 10
matrix = np.arange(2, 11).reshape(3, 3)
print("Original 3x3 Matrix:\n", matrix)

# 2. Convert the array to a float type
float_matrix = matrix.astype(float)
print("\nMatrix converted to Float:\n", float_matrix)

# 3. Flatten the array
flattened_array = float_matrix.reshape(-1)
print("\nFlattened Array:\n", flattened_array)

# 4. Find the maximum and minimum values
max_val = flattened_array.max()
min_val = flattened_array.min()

print(f"\nMaximum Value: {max_val}")
print(f"Minimum Value: {min_val}")

Original 3x3 Matrix:
 [[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]

Matrix converted to Float:
 [[ 2.  3.  4.]
 [ 5.  6.  7.]
 [ 8.  9. 10.]]

Flattened Array:
 [ 2.  3.  4.  5.  6.  7.  8.  9. 10.]

Maximum Value: 10.0
Minimum Value: 2.0
